# NumPy Indexing and Selection

In [1]:
import numpy as np

In [3]:
# 创造一个数组对象
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[7]

7

In [5]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [6]:
#Setting a value with index range (Broadcasting)
arr[0:5]=10
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [7]:
# 为arr赋值
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# 切片
slice_of_arr=arr[0:4]
slice_of_arr

array([0, 1, 2, 3])

In [10]:
#更改切片,是对切片的操作，不是对原始数组arr的操作
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99])

In [11]:
#对切片的操作同样会对原始数组产生影响
arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

> Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)
The general format is *arr_2d[row][col]* or *arr_2d[row,col]*. I recommend usually using the comma notation for clarity.

In [13]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
# 二维数组一维索引
arr_2d[1]

array([20, 25, 30])

In [15]:
#二维数组二维索引 方法一（即矩阵里面的一个元素）
arr_2d[2][1]

40

In [16]:
#二维数组二维索引 方法二
arr_2d[2,1]

40

In [18]:
#二维数组二维索引之范围索引
arr_2d[2,0:2]

array([35, 40])

In [19]:
#单一个：表示所有行或者所有列
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
# 求的是行索引：0-1，列索引：1-2，对照原始二维数组查看即可
arr_2d[:2,1:]

## Fancy Indexing
Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

神奇索引不按顺序进行排列，自己选什么就按什么顺序排列

In [22]:
#建立矩阵
arr2d=np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#shape代表数组的长度
arr_length=arr2d.shape[1]
arr_length

10

In [25]:
#建立数组
for i in range(arr_length):
    arr2d[i]=i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [29]:
arr2d[[2,4,3,2]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

## Selection

In [31]:
arr=np.arange(1,11)

In [32]:
# 布尔索引
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
#[]里的内容为真则选择，为假则不选择
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])