# numpy学习笔记

## NumPy 副本和视图

副本是一个数据的完整的拷贝，如果我们对副本进行修改，它不会影响到原始数据，物理内存不在同一位置。

视图是数据的一个别称或引用，通过该别称或引用亦便可访问、操作原有数据，但原有数据不会产生拷贝。如果我们对视图进行修改，它会影响到原始数据，物理内存在同一位置。

**视图一般发生在：**

-   1、numpy 的切片操作返回原数据的视图。
-   2、调用 ndarray 的 view() 函数产生一个视图。

**副本一般发生在：**

-   Python 序列的切片操作，调用deepCopy()函数。
-   调用 ndarray 的 copy() 函数产生一个副本。


## python数据结构
> 需要注意的是python自带数据结构、numpy数据结构与pandas数据结构都不完全一致，需要按情况进行记忆，总结而言，各种语言数据结构都不尽相同。

In [7]:
mylist=[1,2,3]
mylist

[1, 2, 3]

## numpy数据结构

In [2]:
import numpy as np
np.array(mylist)

array([1, 2, 3])

In [3]:
import numpy as np
mymat=[[1,2,3],[4,5,6],[7,8,9]]
mymat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## numpy内置方法
### arange
> 注意是arange不是arrange（安排），指的是范围从1到10的整数集合

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

> arange方法的前两个参数指的是区间的上下限(前闭后开)，第三个参数指的是步长（step）

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## zeros and ones
产生一系列的零和一

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## eye
建立一个单位矩阵

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random
建立随机数数组
### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1)
> 均匀分布
### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
> 标准正态分布
## randint
Return random integers from low (inclusive) to high (exclusive).
> 若有第三个参数，则表示产生随机数的个数

In [13]:
np.random.rand(2)

array([0.30322938, 0.94125047])

In [16]:
np.random.rand(3,4)

array([[0.90286625, 0.4000191 , 0.1250239 , 0.14465875],
       [0.1561864 , 0.99114065, 0.74603968, 0.01226622],
       [0.71953775, 0.6425135 , 0.90709116, 0.18325491]])

In [17]:
np.random.randn(2)

array([-0.76707356, -1.31694361])

In [18]:
np.random.randn(2,3)

array([[-0.03842306,  0.50653733,  1.90041616],
       [ 0.37215042,  0.29976799, -0.13224129]])

In [19]:
np.random.randint(1,200)

49

In [20]:
np.random.randint(1,200,5)

array([102,  74,  87,  80, 164])